### ISSUE TITLE
connection refused: connect

### ISSUE THREAD

**Issue by Fricofresh** [PUMAzubis/AzubiWeb#1]
Beim starten der Applikation kommt diese Fehlermeldung: 
```java
java.net.ConnectException: Connection refused: connect 
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_144] 
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_144]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_144]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_144]
	at org.hsqldb.server.HsqlSocketFactory.createSocket(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	... 5 common frames omittedt

**Comment by Fricofresh** [comment]
Lösung: Der Datenbankserver läuft nicht oder stelle sicher, dass die `application.property` in einen `source` Ordner enthalten ist. Normalerweise sollte der übergeordnete Ordner `resources` bereits im BuildPath hinzugefügt sein.
