### ISSUE TITLE
Benutzer Löschen läuft auf Fehler

### ISSUE THREAD

**Issue by Fricofresh** [PUMAzubis/AzubiWeb#9]
Beim löschen eines Benutzers tritt folgender Fehler auf:

```org.apache.wicket.WicketRuntimeException: The component(s) below failed to render. Possible reasons could be that:
	1) you have added a component in code but forgot to reference it in the markup (thus the component will never be rendered),
	2) if your components were added in a parent container then make sure the markup for the child container includes them in <wicket:extend>.

1. [WebMarkupContainer [Component id = erfolgreicherAlertLabelParent, page = de.dpma.azubiweb.view.BenutzerListe, path = erfolgreicherAlertLabelParent, type = org.apache.wicket.markup.html.WebMarkupContainer, isVisible = true, isVersioned = true], children =  [Component id = erfolgreicherAlertLabel]]
2. [Component id = erfolgreicherAlertLabel, page = de.dpma.azubiweb.view.BenutzerListe, path = erfolgreicherAlertLabelParent:erfolgreicherAlertLabel, type = org.apache.wicket.markup.html.basic.Label, isVisible = true, isVersioned = true]

	at org.apache.wicket.Page.checkRendering(Page.java:663) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Page.onAfterRender(Page.java:806) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.markup.html.WebPage.onAfterRender(WebPage.java:209) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Component.afterRender(Component.java:907) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Component.render(Component.java:2247) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Page.renderPage(Page.java:998) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:912) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65) ~[wicket-request-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:283) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:262) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:204) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:286) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]

2018-09-09 21:56:25.940  WARN 14368 --- [nio-8080-exec-1] RequestCycleExtra                        : ********************************
2018-09-09 21:56:25.941 ERROR 14368 --- [nio-8080-exec-1] o.apache.wicket.DefaultExceptionMapper   : Unexpected error occurred

org.apache.wicket.WicketRuntimeException: The component(s) below failed to render. Possible reasons could be that:
	1) you have added a component in code but forgot to reference it in the markup (thus the component will never be rendered),
	2) if your components were added in a parent container then make sure the markup for the child container includes them in <wicket:extend>.

1. [WebMarkupContainer [Component id = erfolgreicherAlertLabelParent, page = de.dpma.azubiweb.view.BenutzerListe, path = erfolgreicherAlertLabelParent, type = org.apache.wicket.markup.html.WebMarkupContainer, isVisible = true, isVersioned = true], children =  [Component id = erfolgreicherAlertLabel]]
2. [Component id = erfolgreicherAlertLabel, page = de.dpma.azubiweb.view.BenutzerListe, path = erfolgreicherAlertLabelParent:erfolgreicherAlertLabel, type = org.apache.wicket.markup.html.basic.Label, isVisible = true, isVersioned = true]

	at org.apache.wicket.Page.checkRendering(Page.java:663) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Page.onAfterRender(Page.java:806) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.markup.html.WebPage.onAfterRender(WebPage.java:209) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Component.afterRender(Component.java:907) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Component.render(Component.java:2247) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.Page.renderPage(Page.java:998) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:912) ~[wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65) ~[wicket-request-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:283) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:262) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:204) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:286) [wicket-core-8.0.0-M9.jar:8.0.0-M9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_181]```

**Comment by Fricofresh** [comment]
behoben mit commit bab654d8b73b3a9c9776309841ab3cf8a25c1320
